rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: test/gemfiles/Gemfile.rails-3.1.x
    - rvm: jruby-19mode
      gemfile: test/gemfiles/Gemfile.rails-3.2.x
